apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: bytefreezer-proxy-dev
  namespace: bytefreezer-dev

bases:
  - ../../base

namePrefix: dev-
namespace: bytefreezer-dev

commonLabels:
  environment: development
  app.kubernetes.io/instance: bytefreezer-proxy-dev

images:
  - name: ghcr.io/n0needt0/bytefreezer-proxy
    newTag: latest

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: bytefreezer-proxy
  - patch: |-
      - op: replace
        path: /spec/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/resources/limits/cpu
        value: "250m"
    target:
      kind: Deployment
      name: bytefreezer-proxy